# Generated by Django 4.0.2 on 2022-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_mapword'),
    ]

    operations = [
        migrations.AddField(
            model_name='myword',
            name='map_words',
            field=models.ManyToManyField(blank=True, null=True, related_name='map_words', to='cloud.MapWord'),
        ),
        migrations.AlterField(
            model_name='myword',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, related_name='links', to='cloud.Link'),
        ),
    ]
